/**
 * Admin endpoint to manually generate and send intake reports
 * POST /api/admin/send-report
 */

import { NextRequest, NextResponse } from 'next/server';
import { createTavusClient } from '@/lib/tavus-client';
import { analyzeTranscript } from '@/lib/transcript-analyzer';
import { generateIntakeReportPDF } from '@/lib/pdf-generator';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { conversationId, recipientEmail, ccEmail, patientName } = body;

    if (!conversationId) {
      return NextResponse.json({ error: 'conversationId is required' }, { status: 400 });
    }

    if (!recipientEmail) {
      return NextResponse.json({ error: 'recipientEmail is required' }, { status: 400 });
    }

    console.log(`[Admin] Generating report for conversation: ${conversationId}`);

    // Fetch conversation with verbose data (includes transcript)
    const client = createTavusClient();

    // Get basic conversation info
    const conversation = await client.getConversation(conversationId, false);
    console.log('[Admin] Conversation status:', conversation.status);

    // Get verbose data for transcript
    const verboseData = await client.getConversation(conversationId, true);
    console.log('[Admin] Got verbose data');

    // Extract transcript from events array
    const events = (verboseData as any).events || [];
    const transcriptEvent = events.find(
      (e: any) => e.event_type === 'application.transcription_ready'
    );
    const transcript = transcriptEvent?.properties?.transcript;

    if (!transcript || transcript.length === 0) {
      return NextResponse.json({
        error: 'No transcript available for this conversation',
        conversationStatus: conversation.status,
        eventsFound: events.map((e: any) => e.event_type)
      }, { status: 400 });
    }

    console.log(`[Admin] Found transcript with ${transcript.length} messages`);

    // Extract perception analysis if available
    const perceptionEvent = events.find(
      (e: any) => e.event_type === 'application.perception_analysis'
    );
    const perceptionAnalysis = perceptionEvent?.properties?.analysis || null;

    // Analyze transcript with Claude
    console.log('[Admin] Analyzing transcript with Claude...');
    const analysis = await analyzeTranscript(transcript);

    // Generate PDF
    console.log('[Admin] Generating PDF...');
    const pdfBuffer = await generateIntakeReportPDF({
      analysis,
      transcript,
      conversationId,
      sessionId: `manual-${Date.now()}`,
      patientName: patientName || 'Unknown Patient',
      perceptionAnalysis,
    });

    // Send email
    console.log(`[Admin] Sending email to ${recipientEmail}...`);
    const emailRecipients = ccEmail ? [recipientEmail, ccEmail] : [recipientEmail];

    const emailResult = await resend.emails.send({
      from: 'Flo AI Intake <flo@narrator.studio>',
      to: emailRecipients,
      subject: `AI Intake Report - ${patientName || 'Patient'} - ${new Date().toLocaleDateString()}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #1a1a1a;">AI Intake Report</h1>
          <p>Attached is the intake report from the AI nursing assistant conversation.</p>
          <hr style="border: 1px solid #eee; margin: 20px 0;" />
          <p style="color: #666; font-size: 12px;">
            Generated by Flo AI Intake System<br />
            Conversation ID: ${conversationId}<br />
            Date: ${new Date().toISOString()}
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `intake-report-${conversationId.slice(0, 8)}.pdf`,
          content: pdfBuffer.toString('base64'),
        },
      ],
    });

    console.log('[Admin] Email result:', JSON.stringify(emailResult, null, 2));

    if (emailResult.error) {
      return NextResponse.json({
        success: false,
        error: 'Email send failed',
        emailError: emailResult.error,
        conversationId,
      }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: 'Report generated and sent',
      conversationId,
      recipientEmail,
      ccEmail,
      transcriptMessages: transcript.length,
      hasPerceptionAnalysis: !!perceptionAnalysis,
      emailId: emailResult.data?.id,
      emailResult: emailResult,
    });

  } catch (error) {
    console.error('[Admin] Error generating report:', error);
    return NextResponse.json({
      error: 'Failed to generate report',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}
